// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import url "github.com/kpr-hellofresh/tinyurl/internal/domain/url"

// Adder is an autogenerated mock type for the Adder type
type Adder struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, _a1
func (_m *Adder) Add(ctx context.Context, _a1 url.URL) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, url.URL) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
