// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import url "github.com/kpr-hellofresh/tinyurl/internal/domain/url"

// Getter is an autogenerated mock type for the Getter type
type Getter struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, id
func (_m *Getter) Get(ctx context.Context, id string) (url.URL, error) {
	ret := _m.Called(ctx, id)

	var r0 url.URL
	if rf, ok := ret.Get(0).(func(context.Context, string) url.URL); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(url.URL)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
